# Zeabur 配置文件
version: v1

# 服务配置
services:
  - name: ashtanga-app
    type: prebuilt
    # 构建配置
    build:
      type: nodejs
      builder: nixpacks
      # Nixpacks 配置
      nixpacks:
        # 指定 Node.js 版本
        nodeVersion: "20"
        # 包管理器
        packageManager: pnpm
        # 安装命令
        install:
          - pnpm install
        # 构建命令
        build:
          - pnpm build
        # 启动命令
        start:
          - pnpm start
        # 环境变量
        env:
          - key: NODE_ENV
            value: production
          - key: PORT
            value: "8080"
    # 端口配置
    ports:
      - port: 8080
        type: http
        expose: true
