export interface VinyasaStep {
  count: string
  breath: string
  action: string
  drishti?: string
  isAsana?: boolean
  holdBreaths?: number
}

export interface SuryaStepInstruction {
  count: string
  cueName: string
  breath: string
  drishti: string
  drishtiSanskrit: string
  action: string
  vinyasaCount: number
  holdBreaths?: number
}

export interface StandingInstruction {
  sanskrit: string
  cueName: string
  aliases: string[]
  vinyasaCount?: number
  drishti: string
  drishtiSanskrit: string
  steps: VinyasaStep[]
}

const step = (
  count: string,
  breath: string,
  action: string,
  options: Pick<VinyasaStep, 'drishti' | 'isAsana' | 'holdBreaths'> = {},
): VinyasaStep => ({ count, breath, action, ...options })

export const SURYA_STEPS: Record<string, SuryaStepInstruction> = {
  'surya-a/surya-a-01.png': {
    count: 'Samasthitiḥ',
    cueName: '山式（准备）',
    breath: '准备',
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    action: '山式站立，准备进入拜日式 A。',
    vinyasaCount: 9,
  },
  'surya-a/surya-a-02.png': {
    count: 'Ekam',
    cueName: '双臂上举',
    breath: '吸气',
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    action: '双手举过头合十，微微抬头。',
    vinyasaCount: 9,
  },
  'surya-a/surya-a-03.png': {
    count: 'Dve',
    cueName: '站立前屈',
    breath: '呼气',
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    action: '前弯，手放脚掌两边，鼻尖碰膝盖。',
    vinyasaCount: 9,
  },
  'surya-a/surya-a-04.png': {
    count: 'Trīṇi',
    cueName: '半前屈',
    breath: '吸气',
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    action: '抬头。',
    vinyasaCount: 9,
  },
  'surya-a/surya-a-05.png': {
    count: 'Catvāri',
    cueName: '四柱支撑',
    breath: '呼气',
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    action: '跳或走到平板式，身体保持一直线。',
    vinyasaCount: 9,
  },
  'surya-a/surya-a-06.png': {
    count: 'Pañca',
    cueName: '上犬式',
    breath: '吸气',
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    action: '胸口往前送，后弯进入上犬式。',
    vinyasaCount: 9,
  },
  'surya-a/surya-a-07.png': {
    count: 'Ṣaṭ',
    cueName: '下犬式',
    breath: '呼气',
    drishti: '肚脐',
    drishtiSanskrit: 'nābhicakre',
    action: '腰部上提，脚跟踩地，进入下犬式。',
    vinyasaCount: 9,
    holdBreaths: 5,
  },
  'surya-a/surya-a-08.png': {
    count: 'Sapta',
    cueName: '半前屈',
    breath: '吸气',
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    action: '跳回两手之间，抬头。',
    vinyasaCount: 9,
  },
  'surya-a/surya-a-09.png': {
    count: 'Aṣṭau',
    cueName: '站立前屈',
    breath: '呼气',
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    action: '前弯，鼻尖碰膝盖。',
    vinyasaCount: 9,
  },
  'surya-a/surya-a-10.png': {
    count: 'Nava',
    cueName: '双臂上举',
    breath: '吸气',
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    action: '起身，双手举过头合十。',
    vinyasaCount: 9,
  },
  'surya-a/surya-a-11.png': {
    count: 'Samasthitiḥ',
    cueName: '山式',
    breath: '呼气',
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    action: '回到山式。',
    vinyasaCount: 9,
  },
  'surya-b/surya-b-01.png': {
    count: 'Samasthitiḥ',
    cueName: '山式（准备）',
    breath: '准备',
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    action: '山式站立，准备进入拜日式 B。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-02.png': {
    count: 'Ekam',
    cueName: '坐椅式',
    breath: '吸气',
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    action: '屈膝，手臂高举过头合十。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-03.png': {
    count: 'Dve',
    cueName: '站立前屈',
    breath: '呼气',
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    action: '腿打直前弯，鼻尖碰膝盖。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-04.png': {
    count: 'Trīṇi',
    cueName: '半前屈',
    breath: '吸气',
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    action: '抬头。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-05.png': {
    count: 'Catvāri',
    cueName: '四柱支撑',
    breath: '呼气',
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    action: '进入平板式，身体保持一直线。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-06.png': {
    count: 'Pañca',
    cueName: '上犬式',
    breath: '吸气',
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    action: '进入上犬式。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-07.png': {
    count: 'Ṣaṭ',
    cueName: '下犬式',
    breath: '呼气',
    drishti: '肚脐',
    drishtiSanskrit: 'nābhicakre',
    action: '进入下犬式。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-08.png': {
    count: 'Sapta',
    cueName: '英雄式 A（右侧）',
    breath: '吸气',
    drishti: '指尖',
    drishtiSanskrit: 'hastāgre',
    action: '右脚踩到两手之间，右膝蹲低，左腿打直，手臂高举。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-09.png': {
    count: 'Aṣṭau',
    cueName: '四柱支撑',
    breath: '呼气',
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    action: '回到平板式。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-10.png': {
    count: 'Nava',
    cueName: '上犬式',
    breath: '吸气',
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    action: '进入上犬式。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-11.png': {
    count: 'Daśa',
    cueName: '下犬式',
    breath: '呼气',
    drishti: '肚脐',
    drishtiSanskrit: 'nābhicakre',
    action: '进入下犬式。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-12.png': {
    count: 'Ekādaśa',
    cueName: '英雄式 A（左侧）',
    breath: '吸气',
    drishti: '指尖',
    drishtiSanskrit: 'hastāgre',
    action: '左脚踩到两手之间，左膝蹲低，右腿打直，手臂高举。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-13.png': {
    count: 'Dvādaśa',
    cueName: '四柱支撑',
    breath: '呼气',
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    action: '回到平板式。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-14.png': {
    count: 'Trayodaśa',
    cueName: '上犬式',
    breath: '吸气',
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    action: '进入上犬式。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-15.png': {
    count: 'Caturdaśa',
    cueName: '下犬式',
    breath: '呼气',
    drishti: '肚脐',
    drishtiSanskrit: 'nābhicakre',
    action: '进入下犬式。',
    vinyasaCount: 17,
    holdBreaths: 5,
  },
  'surya-b/surya-b-16.png': {
    count: 'Pañcadaśa',
    cueName: '半前屈',
    breath: '吸气',
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    action: '跳回两手之间，抬头。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-17.png': {
    count: 'Ṣoḍaśa',
    cueName: '站立前屈',
    breath: '呼气',
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    action: '前弯，鼻尖碰膝盖。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-18.png': {
    count: 'Saptadaśa',
    cueName: '坐椅式',
    breath: '吸气',
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    action: '屈膝起身，手臂高举过头合十。',
    vinyasaCount: 17,
  },
  'surya-b/surya-b-19.png': {
    count: 'Samasthitiḥ',
    cueName: '山式',
    breath: '呼气',
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    action: '回到山式。',
    vinyasaCount: 17,
  },
}

const utthitaHasta1Steps: VinyasaStep[] = [
  step('1', '吸气', '左手叉腰，右手往前伸直，提右腿，右手勾右脚大拇指，膝盖打直，挺胸提腰。'),
  step('2', '呼气', '上半身前倾，鼻子碰右膝。', { drishti: '脚趾', isAsana: true, holdBreaths: 5 }),
  step('3', '吸气', '抬头挺胸，回到第 1 动位置。'),
  step('4', '呼气', '右腿往右边打开，臂腿腰胸都打直，眼看左边。', { drishti: '侧边' }),
  step('5', '吸气', '右腿拉回正面，回到第 1 动位置。'),
  step('6', '呼气', '继续把腿抬高，身体前倾，鼻子碰右膝。'),
  step('7', '吸气', '抬头挺胸腰直，两手叉腰，右腿继续提高打直。', { drishti: '脚趾' }),
  step('8', '呼气后吸气', '放下右腿；接着提左腿，左手勾左脚大拇指。'),
  step('9', '呼气', '上半身前倾，鼻子碰左膝。', { drishti: '脚趾', isAsana: true, holdBreaths: 5 }),
  step('10', '吸气', '抬头挺胸，回到第 8 动位置。'),
  step('11', '呼气', '左腿往左边打开，臂腿腰胸都打直，眼看右边。', { drishti: '侧边' }),
  step('12', '吸气', '左腿拉回正面，回到第 8 动位置。'),
  step('13', '呼气', '继续把腿抬高，身体前倾，鼻子碰左膝。'),
  step('14', '吸气', '抬头挺胸腰直，两手叉腰，左腿继续提高打直。', { drishti: '脚趾' }),
  step('—', '呼气', '放下左腿，回到山式。'),
]

const utthitaHasta2Steps: VinyasaStep[] = [
  step('1', '吸气', '左手叉腰，右手往前伸直，提右腿，右手勾右脚大拇指，膝盖打直，挺胸提腰。'),
  step('2', '呼气', '上半身前倾，鼻子碰右膝。', { drishti: '脚趾' }),
  step('3', '吸气', '抬头挺胸，回到第 1 动位置。'),
  step('4', '呼气', '右腿往右边打开，臂腿腰胸都打直，眼看左边。', { drishti: '侧边', isAsana: true, holdBreaths: 5 }),
  step('5', '吸气', '右腿拉回正面，回到第 1 动位置。'),
  step('6', '呼气', '继续把腿抬高，身体前倾，鼻子碰右膝。'),
  step('7', '吸气', '抬头挺胸腰直，两手叉腰，右腿继续提高打直。', { drishti: '脚趾' }),
  step('8', '呼气后吸气', '放下右腿；接着提左腿，左手勾左脚大拇指。'),
  step('9', '呼气', '上半身前倾，鼻子碰左膝。', { drishti: '脚趾' }),
  step('10', '吸气', '抬头挺胸，回到第 8 动位置。'),
  step('11', '呼气', '左腿往左边打开，臂腿腰胸都打直，眼看右边。', { drishti: '侧边', isAsana: true, holdBreaths: 5 }),
  step('12', '吸气', '左腿拉回正面，回到第 8 动位置。'),
  step('13', '呼气', '继续把腿抬高，身体前倾，鼻子碰左膝。'),
  step('14', '吸气', '抬头挺胸腰直，两手叉腰，左腿继续提高打直。', { drishti: '脚趾' }),
  step('—', '呼气', '放下左腿，回到山式。'),
]

const utthitaHasta3Steps: VinyasaStep[] = [
  step('1', '吸气', '左手叉腰，右手往前伸直，提右腿，右手勾右脚大拇指，膝盖打直，挺胸提腰。'),
  step('2', '呼气', '上半身前倾，鼻子碰右膝。', { drishti: '脚趾' }),
  step('3', '吸气', '抬头挺胸，回到第 1 动位置。'),
  step('4', '呼气', '右腿往右边打开，臂腿腰胸都打直，眼看左边。', { drishti: '侧边' }),
  step('5', '吸气', '右腿拉回正面，回到第 1 动位置。'),
  step('6', '呼气', '继续把腿抬高，身体前倾，鼻子碰右膝。'),
  step('7', '吸气', '抬头挺胸腰直，两手叉腰，右腿继续提高打直。', { drishti: '脚趾', isAsana: true, holdBreaths: 5 }),
  step('8', '呼气后吸气', '放下右腿；接着提左腿，左手勾左脚大拇指。'),
  step('9', '呼气', '上半身前倾，鼻子碰左膝。', { drishti: '脚趾' }),
  step('10', '吸气', '抬头挺胸，回到第 8 动位置。'),
  step('11', '呼气', '左腿往左边打开，臂腿腰胸都打直，眼看右边。', { drishti: '侧边' }),
  step('12', '吸气', '左腿拉回正面，回到第 8 动位置。'),
  step('13', '呼气', '继续把腿抬高，身体前倾，鼻子碰左膝。'),
  step('14', '吸气', '抬头挺胸腰直，两手叉腰，左腿继续提高打直。', { drishti: '脚趾', isAsana: true, holdBreaths: 5 }),
  step('—', '呼气', '放下左腿，回到山式。'),
]

export const STANDING_INSTRUCTIONS: Record<string, StandingInstruction> = {
  'standing/padangusthasana.png': {
    sanskrit: 'Pādāṅguṣṭhāsana',
    cueName: '手抓脚趾前弯式',
    aliases: ['手抓大脚趾式'],
    vinyasaCount: 3,
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    steps: [
      step('1', '吸气', '两脚跳开半呎（约 15 cm），手勾脚大拇趾，抬头挺胸。'),
      step('2', '呼气', '前弯，头靠近两膝之间，腿打直。', { isAsana: true, holdBreaths: 5 }),
      step('3', '吸气', '抬头，手指继续勾脚大拇指。'),
      step('—', '呼气', '回到山式。'),
    ],
  },
  'standing/padahastasana.png': {
    sanskrit: 'Pāda Hastāsana',
    cueName: '脚踩手掌前弯式',
    aliases: ['手压脚掌式', '手在脚下式'],
    vinyasaCount: 3,
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    steps: [
      step('1', '吸气', '两脚跳开半呎（约 15 cm）；呼气把两只手掌踩在脚掌下；再吸气抬头挺胸。'),
      step('2', '呼气', '头靠近两膝之间，膝盖打直。', { isAsana: true, holdBreaths: 5 }),
      step('3', '吸气', '抬头。'),
      step('—', '呼气', '回到山式。'),
    ],
  },
  'standing/trikonasana-01.png': {
    sanskrit: 'Utthita Trikoṇāsana',
    cueName: '三角式',
    aliases: ['三角伸展式'],
    vinyasaCount: 5,
    drishti: '手指',
    drishtiSanskrit: 'hastāgre',
    steps: [
      step('1', '吸气', '面向右边，脚跳开三呎，手臂往两侧张开与胸同高。'),
      step('2', '呼气', '右脚往右转，右手抓住右脚大拇趾，左手往上举高，眼睛看指尖。', { isAsana: true, holdBreaths: 5 }),
      step('3', '吸气', '回到第 1 动位置。'),
      step('4', '呼气', '左脚往左转，左手抓住左脚大拇趾，右手往上举高，眼睛看指尖。', { isAsana: true, holdBreaths: 5 }),
      step('5', '吸气', '回到第 1 动位置。'),
      step('—', '呼气', '回到山式。'),
    ],
  },
  'standing/trikonasana-02.png': {
    sanskrit: 'Parivṛtta Trikoṇāsana',
    cueName: '反三角式',
    aliases: ['扭转三角式'],
    vinyasaCount: 5,
    drishti: '手指',
    drishtiSanskrit: 'hastāgre',
    steps: [
      step('1', '吸气', '面向右边，脚跳开三呎，手臂往两侧张开。'),
      step('2', '呼气', '右脚往右转，左手放右脚外侧地上，右手往上举高，扭转，眼睛看指尖。', { isAsana: true, holdBreaths: 5 }),
      step('3', '吸气', '回到第 1 动位置。'),
      step('4', '呼气', '换左边，扭转停留，眼睛看指尖。', { isAsana: true, holdBreaths: 5 }),
      step('5', '吸气', '回到第 1 动位置。'),
      step('—', '呼气', '回到山式。'),
    ],
  },
  'standing/parsvakonasana-01.png': {
    sanskrit: 'Utthita Pārśvakoṇāsana',
    cueName: '侧角式',
    aliases: ['侧角伸展式'],
    vinyasaCount: 5,
    drishti: '手指',
    drishtiSanskrit: 'hastāgre',
    steps: [
      step('1', '吸气', '面向右边，脚跳开五呎，手臂往两侧伸直与胸同高。'),
      step('2', '呼气', '右脚往右转，右膝蹲低，右手放右脚外侧，左臂在耳边伸直。', { isAsana: true, holdBreaths: 5 }),
      step('3', '吸气', '回到第 1 动位置。'),
      step('4', '呼气', '换左边，动作同右边。', { isAsana: true, holdBreaths: 5 }),
      step('5', '吸气', '回到第 1 动位置。'),
      step('—', '呼气', '回到山式。'),
    ],
  },
  'standing/parsvakonasana-02.png': {
    sanskrit: 'Parivṛtta Pārśvakoṇāsana',
    cueName: '反侧角式',
    aliases: ['扭转侧角式'],
    vinyasaCount: 5,
    drishti: '手指',
    drishtiSanskrit: 'hastāgre',
    steps: [
      step('1', '吸气', '面向右边，脚跳开五呎，手臂往两侧伸直。'),
      step('2', '呼气', '右脚往右转，右膝蹲低，左手臂绕过右膝外侧，双手合十或右臂在耳边伸直，身体扭转。', { isAsana: true, holdBreaths: 5 }),
      step('3', '吸气', '回到第 1 动位置。'),
      step('4', '呼气', '换左边，扭转停留。', { isAsana: true, holdBreaths: 5 }),
      step('5', '吸气', '回到第 1 动位置。'),
      step('—', '呼气', '回到山式。'),
    ],
  },
  'standing/prasarita-padottanasana-a.png': {
    sanskrit: 'Prasārita Pādottānāsana A',
    cueName: '开腿前弯式 A',
    aliases: ['双角式 A', '宽腿前屈式 A'],
    vinyasaCount: 5,
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    steps: [
      step('1', '吸气', '面向右侧，脚跳开五呎，手叉腰。'),
      step('2', '呼气后吸气', '前弯，双手放地板上；接着抬头挺胸。'),
      step('3', '呼气', '前弯，头顶放地板。', { isAsana: true, holdBreaths: 5 }),
      step('4', '吸气', '抬头，手推地起身。'),
      step('5', '呼气', '回到第 1 动位置。'),
      step('—', '呼气', '回到山式。'),
    ],
  },
  'standing/prasarita-padottanasana-b.png': {
    sanskrit: 'Prasārita Pādottānāsana B',
    cueName: '开腿前弯式 B',
    aliases: ['双角式 B', '宽腿前屈式 B'],
    vinyasaCount: 5,
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    steps: [
      step('1', '吸气', '面向右侧，脚跳开五呎，两手臂往身体两侧伸直，与胸同高。'),
      step('2', '呼气', '手叉腰。'),
      step('3', '吸气后呼气', '抬头挺胸；接着前弯，头顶放地板。', { isAsana: true, holdBreaths: 5 }),
      step('4', '吸气', '抬头起身。'),
      step('5', '呼气', '一个吸吐后回到第 1 动位置。'),
      step('—', '呼气', '回到山式。'),
    ],
  },
  'standing/prasarita-padottanasana-c.png': {
    sanskrit: 'Prasārita Pādottānāsana C',
    cueName: '开腿前弯式 C',
    aliases: ['双角式 C', '宽腿前屈式 C'],
    vinyasaCount: 5,
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    steps: [
      step('1', '吸气', '面向右侧，脚跳开五呎，手叉腰。'),
      step('2', '呼气', '背后十指交扣，挺胸站好。'),
      step('3', '吸气后呼气', '抬头挺胸；接着前弯，头顶放地板。', { isAsana: true, holdBreaths: 5 }),
      step('4', '吸气', '抬头，手推地起身。'),
      step('5', '呼气', '一个吸吐后解开手叉腰，回到第 1 动位置。'),
      step('—', '呼气', '回到山式。'),
    ],
  },
  'standing/prasarita-padottanasana-d.png': {
    sanskrit: 'Prasārita Pādottānāsana D',
    cueName: '开腿前弯式 D',
    aliases: ['双角式 D', '宽腿前屈式 D'],
    vinyasaCount: 5,
    drishti: '眉心',
    drishtiSanskrit: 'bhrūmadhye',
    steps: [
      step('1', '吸气', '面向右侧，脚跳开五呎，手叉腰。'),
      step('2', '呼气', '前弯，两手勾住大脚趾，微微抬头，手臂和背部打直。'),
      step('3', '吸气后呼气', '抬头挺胸；接着把头顶放两脚之间的地板。', { isAsana: true, holdBreaths: 5 }),
      step('4', '吸气', '抬头，手推地起身。'),
      step('5', '呼气', '手解开叉腰，回到第 1 动位置。'),
      step('—', '呼气', '回到山式。'),
    ],
  },
  'standing/parsvottanasana.png': {
    sanskrit: 'Pārśvottānāsana',
    cueName: '侧身延展前弯式',
    aliases: ['加强侧伸展式', '侧伸展式'],
    vinyasaCount: 5,
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    steps: [
      step('1', '吸气', '面向右边，脚跳开三呎，双手在背后合十，胸口挺直。'),
      step('2', '呼气', '前弯，鼻子碰右膝，膝盖打直。', { isAsana: true, holdBreaths: 5 }),
      step('3', '吸气', '抬头起身，转向左边。'),
      step('4', '呼气', '前弯，鼻子碰左膝。', { isAsana: true, holdBreaths: 5 }),
      step('5', '吸气', '回到第 1 动。'),
      step('—', '呼气', '回到山式。'),
    ],
  },
  'standing/utthita-hasta-padangusthasana-01.png': {
    sanskrit: 'Utthita Hasta Pādāṅguṣṭhāsana (1)',
    cueName: '手抓脚趾延展式 (1)',
    aliases: ['单腿手抓大脚趾式', '单腿站立伸展式'],
    vinyasaCount: 14,
    drishti: '脚趾',
    drishtiSanskrit: 'pādāgra',
    steps: utthitaHasta1Steps,
  },
  'standing/utthita-hasta-padangusthasana-02.png': {
    sanskrit: 'Utthita Pārśvasahita (2)',
    cueName: '手抓脚趾延展式 (2)',
    aliases: ['单腿侧伸展式'],
    vinyasaCount: 14,
    drishti: '侧边',
    drishtiSanskrit: 'pārśva',
    steps: utthitaHasta2Steps,
  },
  'standing/utthita-hasta-padangusthasana-03.png': {
    sanskrit: 'Utthita Hasta Pādāṅguṣṭhāsana (3)',
    cueName: '手抓脚趾延展式 (3)',
    aliases: ['单腿前伸式', 'Utthita Hasta Pādāṅguṣṭhāsana B'],
    vinyasaCount: 14,
    drishti: '脚趾',
    drishtiSanskrit: 'pādāgra',
    steps: utthitaHasta3Steps,
  },
  'standing/ardha-baddha-padmottanasana.png': {
    sanskrit: 'Ardha Baddha Padmottānāsana',
    cueName: '半莲花抓脚前弯式',
    aliases: ['半莲花加强前屈式', '半束莲花站立前屈式'],
    vinyasaCount: 9,
    drishti: '鼻尖',
    drishtiSanskrit: 'nāsāgre',
    steps: [
      step('1', '吸气', '右脚盘左大腿上，右手绕背后抓右脚大拇指，左手叉腰。', { isAsana: true }),
      step('2', '呼气', '前弯，左手放左脚旁，鼻子碰膝盖。', { isAsana: true, holdBreaths: 5 }),
      step('3', '吸气', '抬头。'),
      step('4', '呼气后吸气', '身体站直；接着左手叉腰。'),
      step('5', '呼气', '放开右脚，右腿打直。'),
      step('6', '吸气', '左脚盘右大腿上，左手绕背后抓左脚大拇指，右手叉腰。', { isAsana: true }),
      step('7', '呼气', '前弯，右手放右脚旁，鼻子碰膝盖。', { isAsana: true, holdBreaths: 5 }),
      step('8', '吸气', '抬头。'),
      step('9', '呼气后吸气', '右手叉腰；接着身体站直。'),
      step('—', '呼气', '回到山式。'),
    ],
  },
  'standing/utkatasana.png': {
    sanskrit: 'Utkaṭāsana',
    cueName: '坐椅式',
    aliases: ['幻椅式', '椅子式'],
    vinyasaCount: 13,
    drishti: '拇指',
    drishtiSanskrit: 'aṅguṣṭhamadhye',
    steps: [
      step('1–6', '—', '完成拜日式 A 前 6 个动作。'),
      step('7', '吸气', '跳到双手中间，屈膝，手臂高举。', { isAsana: true, holdBreaths: 5 }),
      step('8', '呼气后吸气', '手贴地；接着把重心放手上，下半身提起。'),
      step('9', '呼气', '往后抛到平板式（四柱支撑）。'),
      step('10', '吸气', '胸口前送后弯成上犬式。'),
      step('11', '呼气', '腰上提，脚跟踩地成下犬式。'),
      step('12', '吸气', '跳回两手之间，抬头挺胸。'),
      step('13', '呼气', '前弯，鼻尖碰膝盖，再回山式。'),
    ],
  },
  'standing/virabhadrasana-1.png': {
    sanskrit: 'Vīrabhadrāsana A',
    cueName: '英雄式 A',
    aliases: ['战士一式', '战士式 A', '勇士式 A'],
    vinyasaCount: 16,
    drishti: '手指',
    drishtiSanskrit: 'hastāgre',
    steps: [
      step('1–6', '—', '完成拜日式 A 前 6 个动作。'),
      step('7', '吸气', '右脚往前，右膝蹲低，双臂高举过头合十，掌心并拢，抬头挺胸。', { isAsana: true, holdBreaths: 5 }),
      step('8', '呼气', '转向左边，左膝蹲低，双臂继续高举过头，掌心并拢，抬头挺胸。', { isAsana: true, holdBreaths: 5 }),
      step('9', '吸气', '腿不变，双臂展开与肩同高，看左手指尖。', { isAsana: true, holdBreaths: 5 }),
      step('10', '呼气', '转向右边，右膝蹲低，看右手指尖。', { isAsana: true, holdBreaths: 5 }),
      step('11', '吸气', '双手放右脚两侧，腿提离地板。'),
      step('12', '呼气', '跳到平板式（四柱支撑）。'),
      step('13', '吸气', '胸口前送后弯成上犬式。'),
      step('14', '呼气', '腰上提，脚跟踩地成下犬式。'),
      step('15', '吸气', '跳回两手之间，抬头挺胸。'),
      step('16', '呼气', '前弯，鼻尖碰膝盖，回到山式。'),
    ],
  },
  'standing/virabhadrasana-2.png': {
    sanskrit: 'Vīrabhadrāsana B',
    cueName: '英雄式 B',
    aliases: ['战士二式', '战士式 B', '勇士式 B'],
    vinyasaCount: 16,
    drishti: '拇指',
    drishtiSanskrit: 'aṅguṣṭhamadhye',
    steps: [
      step('1–6', '—', '完成拜日式 A 前 6 个动作。'),
      step('7', '吸气', '右脚往前，右膝蹲低成弓步，双臂平举与肩同高、掌心朝下，眼看右拇指。', { isAsana: true, holdBreaths: 5 }),
      step('8', '呼气', '双手放右脚两侧，跳到平板式（四柱支撑）。'),
      step('9', '吸气', '胸口前送后弯成上犬式。'),
      step('10', '呼气', '腰上提，脚跟踩地成下犬式。'),
      step('11', '吸气', '左脚往前，左膝蹲低成弓步，双臂平举与肩同高、掌心朝下，眼看左拇指。', { isAsana: true, holdBreaths: 5 }),
      step('12', '呼气', '双手放左脚两侧，跳到平板式（四柱支撑）。'),
      step('13', '吸气', '胸口前送后弯成上犬式。'),
      step('14', '呼气', '腰上提，脚跟踩地成下犬式。'),
      step('15', '吸气', '跳回两手之间，抬头挺胸。'),
      step('16', '呼气', '前弯，鼻尖碰膝盖，回到山式。'),
    ],
  },
}
